name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up JDK 17 (Zulu with JavaFX)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.11'
          cache: 'gradle'

      - name: Set up headless mode for TestFX (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -ac &

      - name: Build and test with Gradle
        run: xvfb-run -a ./gradlew check --info
