#@@author appleshill-reused
#reused from https://github.com/nus-cs2103-AY2425S1/ip/pull/3
#with minor modifications
name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.11'
          distribution: 'zulu'
          java-package: jdk+fx

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test --info --stacktrace
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      - name: Test with Gradle
        run: ./gradlew test --info --stacktrace --no-parallel --no-daemon
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      - name: List running processes (Unix)
        if: runner.os != 'Windows'
        run: ps aux

      - name: List running processes (Windows)
        if: runner.os == 'Windows'
        run: Get-Process | Select-Object Id, ProcessName, CPU

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test
