#@@author appleshill-reused
#reused from https://github.com/nus-cs2103-AY2425S1/ip/pull/3
#with minor modifications
name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      # Checkout the repository
      - name: Set up repository
        uses: actions/checkout@v4

      # Set up JDK 17 (with JavaFX if needed)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.11'
          distribution: 'zulu'
          java-package: jdk+fx

      # Validate the Gradle wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # Checks the style, making sure no style violations
      - name: Test style using Gradle
        run: ./gradlew checkStyleMain checkStyleTest
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      # Build and run tests with Gradle
      - name: Build and test with Gradle
        run: ./gradlew clean build test
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}